volumes:
  mysql:
  phpmyadmin:

networks:
  app:
    driver: bridge
    attachable: true

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lab3
    volumes:
      - mysql:/var/lib/mysql
      - ./lab3.sql:/docker-entrypoint-initdb.d/lab3.sql
    ports:
      - "13306:3306"
    networks:
      app:
        aliases:
          - db
          - mysql

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "4000:4000"
    networks:
      app:
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ui/static:/app/static
      - ./ssl:/etc/nginx/ssl
      - ./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
    networks:
      app:
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
    ports:
      - "6672:80"
    depends_on:
      - mysql
    networks:
      app:
